### ISSUE TITLE
issue#1

### ISSUE THREAD

**Issue by ropili19** [ropili19/IWVG.SwC.RosarioOrbezo#1]
[Issue#1](https://github.com/ropili19/IWVG.SwC.RosarioOrbezo/wiki/Point)

**Comment by AngelicaGuaman** [comment]
Hola Rosario, también habría que modificar los métodos **module**, **phase**, **translateOrigin**?

**Comment by ropili19** [comment]
Hola Angélica, no, solo el método translateOrigin. gracias.

**Comment by AngelicaGuaman** [comment]
Ok, entonces cambiaré los nombre de los métodos module y phase porque solo se hacen sobre las coordenada X e Y.

**Comment by ropili19** [comment]
vale, me parece bien,gracias angélica
